### ISSUE TITLE
OSX : Errors prevented startup: While loading plugin `compileScss` from package `fourseven:scss`

### ISSUE THREAD

**Issue by lc3t35** [fourseven/meteor-scss#95]
From here : https://github.com/SpaceTalk/SpaceTalk/issues/117

On OSX 10.8.5, 
````
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading plugin `compileScss` from package `fourseven:scss`:
   module.js:356:32:
   dlopen(/Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node,
   1): Symbol not found: __ZNSt12out_of_rangeD1Ev
   Referenced from:
   /Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   Expected in: /usr/lib/libstdc++.6.dylib
   in
   /Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:16:15)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require
   (/Users/laurent/.meteor/packages/meteor-tool/.1.1.3.1mvydc8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1341:22)
   at Package (packages/compileScss/plugin/compile-scss.js:2:1)
   at <runJavaScript-30>:146:4
   at <runJavaScript-30>:153:3
=> Your application has errors. Waiting for file change.
````

**Comment by fourseven** [comment]
Doh, I built 3.1.1 on my own box because the build chain wasn't working, so I'll fix it with 3.1.2 (which I need to publish soon).

**Comment by justan0therdave** [comment]
I have the same problem - any idea when you might be able to work on and close this issue?

**Comment by fourseven** [comment]
Hi, the newer versions of libsass included with this need a newer version of the compiler, so I can't build them with the build boxes anymore. Honestly, 3.x series will probably only work with OS X 10.9+, are you able to use `2.1.1` instead?

**Comment by tadeo** [comment]
I have the same problem. How could I install 2.1.1? Thanks!

**Comment by sebakerckhof** [comment]
Can this be closed as a wontfix?

**Comment by sebakerckhof** [comment]
Closing due to inactivity and it's about a really old version.

**Comment by durjoy28** [comment]
> \MeteorProjects\webapp>meteor
[[[[[ ~\E\MeteorProjects\webapp ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3003.
=> Errors prevented startup:

   While loading plugin `vue-component` from package `akryum:vue-component`:
   module.js:547:15: Cannot find module
   'C:\Users\Durjoy\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@babel\runtime\helpers\builtin\interopRequireDefault'
   at Function.Module._resolveFilename (module.js:547:15)
   at Function.Module._load (module.js:474:25)
   at Module.require (module.js:596:17)
   at require (internal/module.js:11:18)
   at Object.require (C:\tools\isobuild\bundler.js:2083:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
   at require (packages/modules-runtime.js:244:16)
   at tag-handler.js (<runJavaScript-33>:623:30)
   at fileEvaluate (packages/modules-runtime.js:339:7)
   at require (packages/modules-runtime.js:238:16)
   at <runJavaScript-33>:2236:1
   at <runJavaScript-33>:2243:3


=> Your application has errors. Waiting for file change.
=> Started MongoDB.

> how I will solve it?
